### ISSUE TITLE
API specification is not displayed

### ISSUE THREAD

**Issue by ingoboerner** [linhd-postdata/averell-docker#1]
Is there an API? In the fronend there is a butto "use via API" but clicking on it returns the following error message in the console: 

```
averell-averell-1  | ERROR:    Exception in ASGI application
averell-averell-1  | Traceback (most recent call last):
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
averell-averell-1  |     result = await app(  # type: ignore[func-returns-value]
averell-averell-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
averell-averell-1  |     return await self.app(scope, receive, send)
averell-averell-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
averell-averell-1  |     await super().__call__(scope, receive, send)
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
averell-averell-1  |     await self.middleware_stack(scope, receive, send)
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
averell-averell-1  |     raise exc
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
averell-averell-1  |     await self.app(scope, receive, _send)
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
averell-averell-1  |     await self.app(scope, receive, send)
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
averell-averell-1  |     raise exc
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
averell-averell-1  |     await self.app(scope, receive, sender)
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
averell-averell-1  |     raise e
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
averell-averell-1  |     await self.app(scope, receive, send)
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
averell-averell-1  |     await route.handle(scope, receive, send)
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
averell-averell-1  |     await self.app(scope, receive, send)
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
averell-averell-1  |     response = await func(request)
averell-averell-1  |                ^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
averell-averell-1  |     raw_response = await run_endpoint_function(
averell-averell-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
averell-averell-1  |     return await run_in_threadpool(dependant.call, **values)
averell-averell-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
averell-averell-1  |     return await anyio.to_thread.run_sync(func, *args)
averell-averell-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
averell-averell-1  |     return await get_asynclib().run_sync_in_worker_thread(
averell-averell-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
averell-averell-1  |     return await future
averell-averell-1  |            ^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
averell-averell-1  |     result = context.run(func, *args)
averell-averell-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 258, in api_info
averell-averell-1  |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
averell-averell-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
averell-averell-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 501, in get_api_info
averell-averell-1  |     info = component["api_info"]["serialized_input"]
averell-averell-1  |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
averell-averell-1  | KeyError: 'serialized_input'
```

**Comment by alvp** [comment]
Gradio API is super limited and I didn't know that after I deployed the app. You have access just to the value of the controls (checkd/unchecked, etc...) 

It should be working now, but limited.
